 language: scala

 cache:
   directories:
    - $HOME/.coursier/cache
    - $HOME/.sbt/boot/

 matrix:
   include:
     - jdk: oraclejdk8
       scala: "2.12.8"

 script:
   - sbt clean coverage test coverageReport coverageAggregate
   - find $HOME/.sbt -name "*.lock" | xargs rm

 after_success: "sbt coveralls"

 dist: bionic

 addons:
  apt:
    packages:
      - oracle-java8-installer
